### ISSUE TITLE
Cannot paste into Markdown Pro Editor on iOS

### ISSUE THREAD

**Issue by DustinVenegas** [sn-extensions/advanced-markdown-editor#47] opened 2020-08-12 18:02 UTC
The cut/copy/paste context menu does not appear after tapping and holding in the Markdown Pro editor.

Pasting basic text works with the Basic and Bold editors.

**Comment by JaspalSuri** [comment] 2020-08-13 09:26
I was unable to reproduce this issue in the latest stable version of iOS 13. What version of iOS are you using and (just in case it matters) what iPhone are you using? 

I noticed that the context menu won't appear until some text is entered, though.

**Comment by DustinVenegas** [comment] 2020-08-13 20:35
>  What version of iOS are you using and (just in case it matters) what iPhone are you using?

I'm using iOS 13.6 on an iPhone X.

> I noticed that the context menu won't appear until some text is entered, though.

Yeah, I noticed the same before and tried pasting with and without preexisting text in a note. The context menu failed to appear when I pasted text into both a new note and an note with preexisting text. The cut/copy/paste menu does not open when trying to paste any text into the Markdown Pro editor for me. I've had to switch to the basic editor, paste, and switch back.

There's something else I noticed that might be related. The default iPhone Keyboard will normally replace two spaces back-to-back (space-space) with a period (.) which is useful to end a sentence by hitting space twice. The space-space to period replacement just enters two spaces in the Markdown Pro editor, which is strange to me because the replacement feels like it works ubiquitously.

Here's a [video taken from my iPhone](https://drive.google.com/file/d/13pXhYmxKJYr54o6D9aHAA4UeUg20Sk4I/view?usp=sharing) to demonstrate paste works in the Basic editor but does not in the Markdown Pro editor.

**Comment by DustinVenegas** [comment] 2020-08-13 21:00
> I noticed that the context menu won't appear until some text is entered, though.

Yeah, I've noticed the same behavior before and tried with and without preexisting text. The context menu failed to appear when I pasted text into both a new note and an note with preexisting text. The cut/copy/paste menu does not open when trying to paste text into the Markdown Pro editor.

The default iPhone Keyboard will normally replace two spaces back-to-back (`space-space`) with a period (`.`). This shortcut is used to end a sentence by hitting space twice. The space-space to period replacement just enters two spaces in the Markdown Pro editor, which is strange to me because the replacement feels like it works ubiquitously.

**Comment by DustinVenegas** [comment] 2020-08-13 21:18
Here's a video take from my iPhone to demonstrate paste works in the Basic editor but does not in the Markdown Pro editor.

![video](https://drive.google.com/file/d/13pXhYmxKJYr54o6D9aHAA4UeUg20Sk4I/view?usp=sharing)

**Comment by JaspalSuri** [comment] 2020-08-14 06:41
Hi, thanks so much for the information and the video! I will get in touch with the team about this.

I think with regards to the text replacement issue, it's possible that we might not have control over it due to possible limitations surrounding iOS. That said, I will forward this in a separate report for review!

**Comment by DustinVenegas** [comment] 2020-08-31 16:54
@JaspalSuri, hello, it's been a few weeks and I wanted to follow-up on this bug. Did the team discover an iOS issue that prevents pasting in some Standard Notes editors but not others?

**Comment by JaspalSuri** [comment] 2020-09-01 08:37
Hi, thanks for following up with us. I haven't heard back yet but in an internal build of the iOS app, it appears to be working expected! I will message our mobile dev directly and get back to you as soon as I hear back (before the end of this week at the most).

**Comment by JaspalSuri** [comment] 2020-09-01 08:55
It looks like they are unable to reproduce the issue, either. I hope that version 3.5 will fix this issue on your end as well, when it's released!

**Comment by DustinVenegas** [comment] 2020-09-02 18:30
Sounds good.

Is there an estimated time frame for the 3.5 release? Editing documents on my iPhone and iPad is how I work sometimes. I've had to resort to using Joplin Notes, another OSS notes taking app that supports markdown, to bridge the gap sometimes.

**Edit** Closing. I'll re-file if this is still an issue after the 3.5 release.

**Comment by JaspalSuri** [comment] 2020-09-03 08:12
Since it appears to be fixed in the internal beta, there's not much more info that we'll need, but thank you for offering to help us!

We plan on releasing the beta publicly (on our Slack) after we've ironed out some more bugs, so hopefully it won't be until long that you'll be able to use the updated version of the app.

**Closed as completed** 2020-09-07 06:17 UTC

**Comment by JaspalSuri** [comment] 2020-10-13 11:47
Hi @DustinVenegas,

If you're interested in trying out the mobile beta app, please join the #beta-testers channel on [our Slack](http://standardnotes.org/slack), and review the pinned message(s). 🙂

**Comment by JaspalSuri** [comment] 2021-04-03 00:29
Hi @DustinVenegas,

I haven't been able to reproduce this issue on any of the iOS or iPadOS devices that I have access to. Please let me know if you can still reproduce this issue or have any questions and/or feedback. 🙂
